name: binary_tk
version: 0.1.1
description: >
  Toolkit Library for Binary Data, on Unit, Scanning, and etc.
author: Haruka Sato <as.he.that.doth.serve@gmail.com>
homepage: https://halka9000stg.github.io/binary_tk.html
repository: https://github.com/halka9000stg/binary_tk.git
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  binary: ^3.1.3
  charset: ^2.0.1
  jis0208: ^1.0.1
topics:
  - binary